language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

install: true

before_install:
  - chmod +x ./gradlew